### ISSUE TITLE
chat id / allowed id not working as expected

### ISSUE THREAD

**Issue by Coolykoen** [tonym128/shhh-bot#13]
This one might be my own mistake, but i cant figure this out.

![image](https://github.com/tonym128/shhh-bot/assets/48558949/a1aef132-6df2-4a19-87ef-779d661a711a)

im sure, i have triple checked, i really think i have the same id in my chat id and in allowed chat id. yet whenever i try to restrict acces to only my chat id with the SHHH_ALLOWED_CHAT_IDS=123456 env. it errors out as if it shouldnt work for that id. (replace 123456 with my actual chat id btw)

current compose:
```
version: "3"
services:
  shhhbot:
    container_name: shhhbot
    hostname: shhhbot
    restart: always
    image: ghcr.io/tonym128/shhh-bot
    environment:
      - SHHH_API_KEY=API_KEY
      - SHHH_ALLOWED_CHAT_IDS=123456
      - SHHH_MY_CHAT_ID=123456
```
